apiVersion: v1
kind: ServiceAccount
metadata:
  name: middleware
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
spec:
  selector:
    app: middleware
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-service-upstreams": "lambda:2345"    
      labels:
        app: middleware
    spec:
      serviceAccountName: middleware    
      containers:
        - name: middleware
          image: nicholasjackson/fake-service:v0.26.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LOG_LEVEL'
              value: 'trace'
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'NAME'
              value: 'middleware'
            - name: 'MESSAGE'
              value: 'I am the middleware!'
            - name: 'UPSTREAM_URIS'
              value: 'http://localhost:2345,http://flaky-service.virtual.consul'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: middleware
spec:
  destination:
    name: middleware
  sources:
  - name: frontend
    action: allow


## Service Defaults    
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
spec:
  protocol: http
