apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-blue
---
apiVersion: v1
kind: Service
metadata:
  name: backend-blue
spec:
  selector:
    app: backend-blue
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  labels:
    app: backend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-blue
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: true
      #   consul.hashicorp.com/kubernetes-service: 'backend-blue'
      labels:
        app: backend-blue
    spec:
      containers:
        - name: backend-blue
          image: nicholasjackson/fake-service:v0.26.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'NAME'
              value: 'backend-blue'
            - name: 'MESSAGE'
              value: 'I am the blue backend'

